apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: personal-blog-db
  namespace: production
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-blog-db
  namespace: production
spec:
  selector:
    matchLabels:
      app: personal-blog-db
  template:
    metadata:
      labels:
        app: personal-blog-db
    spec:
      containers:
        - name: postgres
          image: postgres:16
          env:
            - name: POSTGRES_DB
              value: personal_blog
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: personal-blog-db
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: personal-blog-db
                  key: password
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: personal-blog-db
---
apiVersion: v1
kind: Service
metadata:
  name: personal-blog-db
  namespace: production
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: personal-blog-db
