apiVersion: v1
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      creationTimestamp: "2025-05-18T03:34:13Z"
      name: default
      namespace: default
      resourceVersion: "451"
      uid: bbab31eb-2157-41e7-8478-52b42bfa179b
kind: List
metadata:
  resourceVersion: ""
