apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-private
  namespace: frontend
  labels:
    app: nginx-private
spec:
  selector:
    matchLabels:
      app: nginx-private
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: nginx-private
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-private
  namespace: frontend
  labels:
    app: nginx-private
spec:
  ports:
    - port: 80
      name: http
      targetPort: 80
  selector:
    app: nginx-private
