alloy:
  configMap:
    create: false
    name: alloy-config
    key: config.alloy
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi

  mounts:
    # -- Mount /var/log from the host into the container for log collection.
    varlog: true
