---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik
  namespace: authentik
spec:
  encryptedData:
    secret_key: AgCjm1gTunDjmbdslfw4r6/Apro4a83gOK1g2ATZNZF+7rsM5FoVumRCaHpH+k7JK71MwNaEANLLoxodJC2jfqHGMS3/FUiTzG+C3iMqv3Sy60PL45e6mvOsXh+sstpWLJ6BOYd/OkZzYwA4LbTN0hjK6EAD77IjKKt8lgnDetRROjbycoIxQ4xmjiaD5dXp8iJSImtdofI8uQFKe7CnR+sIUe0ZzGhOIcPxK3matmae7XO8U5APBIuNjctIH5iGFSct0ZvtODmAW6E4JiE7VebbVrVo9wcxstJe5lsd3xBpni62VzCjL6ieSW0YCopnZc/JlPOh7BIFGRBxp6OI65d4HpuMNO7z0a0Y+kjrd3ongR+vp6CGMuqCdmeYuKKeUvJmM8bKG0b2Ro/fF/IlyVnrlo02i5cPDjlI5L5L/3jdeO7G/yyxVVbaHcrDHhVuOUoNGaxuVWFQ/q6PejXVOcI+6zxj45bnsKeyZwVFxzS76vIShz7rCcTwKAx/54YgUaJrnKciurtThcE3aZxkJCTQLWjWi/UieuN0Ydr9ohrrlWsehoSjQUqIXSuAtaQlnZpgcK2QxaA6Xu4b5fqou6A0u1g1hPxyDm8GTf80UZjaB5ZqF6Gp/B7OkrvKfgX0DAoBJ+ry+4quz8CDpSs6Qvewk4KPISKqbrOgBSIzt8D8MGdpRpUnOLdWHnDImlhLL5jGK5UZbCfKsKkSaUM=
  template:
    metadata:
      creationTimestamp: null
      name: authentik
      namespace: authentik
