---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-postgres
  namespace: authentik
spec:
  encryptedData:
    password: AgC+mx8Gu0IeH0kCutbUVTqSInV/0l4t2T4e2WHHkOHiHPWhcH3FkSCmAgi8gjOlV2SwMTJRioc8laaPQGWPxbeVy13aEwXxWnjXhqRzIl2V4jUtQF2vTi25gh65oz85DESiINM7/WD5BsPuUe5qoeDa0XxemVvPN4kZcmTbBwa++kjKe3wB46VJyzIHu9/hIAF4jLoW2ZtwJtTjK/55BX66mLTqW1CZHvCpwDDaAMzWoixzm3S8ylvVgAvyjEpKPzigGISnzisCDWqTH3xNXSzdWR4a1wkSNdW/ZxZeer/zAu0/Hm57BnxED/PfvUzKCzOVIIIGay7t6fxspGZkK/lommsvKmBj01/krIJFRMA/by3NWDBgeKppY9JppUMEX94XR40h3HQbNqD5DK1kEyWMKNGD2OpzsnUxWTS8YwnQGbsKo9q8AIK6bEbVqXesTKW3xHTPlcQYWqOe0joR9znO4/Z6Jt7YProoGJkr4qy9Rl5booGn/ZRdT7dayxhbsHvYUHeA2UAB44eTU76AIsmroqYQq9uLIYsO7sp5zrIZ1w2A5/JjVUC99+aeZ9unE5gzL8FiSPjZ1QDuLzXmZPAvNU1I/N3j1yMsWOY/+TQbn3+cMoPAwGgr/hN1+k/PpiSEBfkeODndz0Cj+/S2WkG8VzQIkVCAMPLCAk801f5FbU7YKaY9ykvkCU5FGWFpYnCWCJsLTiX1yqpYC/0=
  template:
    metadata:
      creationTimestamp: null
      name: authentik-postgres
      namespace: authentik
