globalArguments:
  - "--global.sendanonymoususage=false"
  - "--global.checknewversion=false"

additionalArguments:
  - "--serversTransport.insecureSkipverify=true"
  - "--log.level=DEBUG"

deployment:
  enabled: true
  replicas: 1
  annotations: {}
  podAnnotations: {}
  additionalContainers: []
  initContainers: []

ports:
  web:
    port: 80 # redirections are not needed as tls handled by cloudflare
    # redirections:
    #   entryPoint:
    #     to: websecure
    #     scheme: https
    #     permanent: true
  # websecure:
  #   port: 443
  #   tls:
  #     enabled: true

ingressRoute:
  dashboard:
    enabled: false

providers:
  kubernetesCRD:
    enabled: true
    ingressClass: traefik-public
  kubernetesIngress:
    enabled: true
    publishedService:
      enabled: false

rbac:
  enabled: true

service:
  enabled: true
  type: LoadBalancer
  annotations: {}
  labels: {}
  spec:
    loadBalancerIP: 10.60.60.70 # Must be within Metallb range
  loadBalancerSourceRanges: []
  externalIPs: []
