apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-dmz
  namespace: kube-system
  labels:
    app.kubernetes.io/name: traefik-dmz
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik-dmz
  template:
    metadata:
      labels:
        app.kubernetes.io/name: traefik-dmz
    spec:
      serviceAccountName: traefik
      containers:
        - name: traefik-dmz
          image: traefik:v2.10.4 # Use the same version as your current Traefik
          args:
            - "--providers.kubernetescrd"
            - "--providers.kubernetesingress"
            - "--providers.kubernetesingress.ingressclass=traefik-dmz" # This is critical
            - "--entrypoints.web.address=:80"
            - "--entrypoints.websecure.address=:443"
            - "--log.level=INFO"
          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65532
          resources:
            requests:
              cpu: "100m"
              memory: "50Mi"
            limits:
              cpu: "300m"
              memory: "150Mi"
      # If your node has the DMZ network label, add a nodeSelector:
      nodeSelector:
        network: dmz
