apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: kube-system
  annotations:
    metallb.io/address-pool: internal-pool
    # metallb.universe.tf/loadBalancerIPs: 10.60.60.61
spec:
  type: LoadBalancer
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv4
