apiVersion: v1
kind: Service
metadata:
  name: traefik-dmz
  namespace: kube-system
  annotations:
    metallb.io/address-pool: dmz-pool
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: traefik-dmz
  ports:
    - name: web
      port: 80
      targetPort: 80
    - name: websecure
      port: 443
      targetPort: 443
