---
all:
  children:
    master:
      hosts:
        chimera:
          ansible_host: 10.60.60.25
        centaur:
          ansible_host: 10.60.60.26
        cerberus:
          ansible_host: 10.60.60.27
    agent:
      hosts:
        minotaur:
          ansible_host: 10.60.60.28
        basilisk:
          ansible_host: 10.60.60.29
        certus:
          ansible_host: 10.70.70.30
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    ansible_user: lewi0231
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
