---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-credentials
  namespace: development
spec:
  encryptedData:
    .dockerconfigjson: AgC9lYBGHw7OQCUDM5kdAJAWOF6ExpZpMmFm2nLORMEGpBYa+aPK1wJBMk7qOuyh8V70fngPaEmMjz0yUCTbB7+6+3UElfBtLsknA4Fd3q0XavIpgEyy2c4iJ6UhADRh8w463x/B2NuRGPZpLmZkGtsugxV+qXF3lM/zOyLcJzcNcEzfcsz1kiCis5p8nTFNZgtgyud9lOgvo59iF1pEuF/a77gzfe8k55rGyUnPJ5uN6EgFgL7m9ABcHFqpTZk+aKkHVRBPzrCzym2Fg62OdxZW5zEGWUTiXqFTiJSlWFtQ4DNf2H+A3/D8g+PPcOZUuAc7zMOyboyuOJMCO3fMAoARcu1n6zAlOTBid1bfBz2Lmhr0QXnvPtHC8auVEBH5CH86kc+yTbUZlD8tAvBP69wTo/QPPF4xukuofECGTUnaBtNdqmIWDU7Xpyl89xMk1wds1R8wEyqax2sdMFyiTuoF/f3vS58a6ZptEjNMIPdYNQYKQ099o1iVaY9jK461aV5T4fzDfqPzJy7WR0aXSeGxRbodw1BEsZmR2MzfdpQ+txWL/M2f7CISSNaafcn3EuYSemkpG3MaQnPoNQTxkMY+V0gMf2FLV4uvdVd9MXi6Pzf5NnGtnoSGSXwBf1b97jku8NCsUKngXvQmr39H53pS3cga3PL6H05cgqHNB8ELySXVBgrIRnXjegQDvOfeoxY5q+8CwsZjd3/I3B25gQsM2RGvDGl518fJfCx65OXinjhc1aVjzlPFNkuk5woh2ePbIVgkhkEH1E4m0IL5I9vMvRis4bmbvWaf74oaeTDnyg9txCGml4XS/uwBHQNkobCleQLxJQSZpLlpefhEqAdfagjMqPLu+XJ1u/EIiPNze84UaM9lhJEU6bfmOm/jYNbvZnBmJY9fmyoGt+lnwdXjYsm/PtUiJEb4ss4qUR/nHbI=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-credentials
      namespace: development
    type: kubernetes.io/dockerconfigjson
