---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-credentials
  namespace: development
spec:
  encryptedData:
    password: AgB8jaaHGHO6dqD9ZHh/y+Gwjuss1q3IQpdoXJoaAGcmhvMrfPppHVP/i1ZACwEfzg40cQ4e15BactxtEfUuiGAurNNtY2MjpMkFd0J30G+trEB5fuj3z4VWZKk37QQfnCdSwxJ5d4n9l/2K4uSg+sfDpJIQrvNdJ7G0fgZzRctqW7J1m59POYrZ+I+rCpEv4ejHA9RbEfofk0YVwufchJiKeVJ4bQN+h55bOchgIc8NruWtuxo+aErJh8PNFYbT3tVUwROHlqcT/WYLmeCEu++xuPvK6wtBBH3weXLOi5j65u9NfAhUqKCBT4LVu/JRyb5El49Lo6ndBIdiyo4cuk+gBvCZjsvWojAvBSj9kwGkIZQEL9isFUvwRsqvtizWvLnw3x0kU5hXt3GnxS1z/5j78hQ9JjdRCUZ7nssG7KD7JMssAepKP3wBEzzjWyJ1CehD2v7g8A/eFDVC8e1IZFtytG+eDqcfqIpQiPw1NhrkPOxADfQEhjE8MDDqXPfk0aaf1WAFJ6n4711Ljaq5YIyEMTMVlKKTx6+AHSdy8Dd7LzViyk8ay3RMSpTiIwdFdU8u8YwXOt4/PMdt3xxCKqOZaVw2I4t1NaFtZzhBinIo576hnk3PsJHFvIokHvlJ2+ydlZYsB76I+Pdlor9ShghsHNi7Y2LNbCshMvVrpaschmC5x9V92jG547ocarlu0CxzhQcMGfJREItp29udmz2cAO+XJaEvcIWT6SBbRtL06Jp4dF2IPz5h
    username: AgBqL1X9vSYVuPac6yJSjWK1L46eEDfxy/eQu/1A5AV1cX0nPzmBTkCivlNiT5tGYajgtISGdn0lw+7sVawxc9CBFhYj91YrJ3rptvrgRl9cmPAiaAvvpwz1tnwHkh9WvQRYYmx/Y32sKonFOwYzLHC2PPvjoq1hKuI2U4D0FrSXOWa1cQqHEASUCbZIXabiSKw1/X7u/9j7cvnlwAkCdVH4d7ZRyAYgLCv4tR1v6hkY+58N37Y6lDsmNMM+aTHM2fqMdJxCos2G9KepE+gbPK1tOMxj4G79DoeqedN+JVOfsYECPS/Qby2IsykdGojmdTz0fjH4wBF/3A53C+pxhAH4oYKHRMRK9WQzrkuuOf+mOsI6Ggpg8nXr0Roj18Yv1nUKFcxaLuVo2rAcbysCwSVzJPs8Vb11gyLRtFNvTFdnTOl0dSI7vRO50Fr1xPGWygP+qR2yjEyuiat5kt86AZ9klKhRb79x+3OILh8XlovEZxxmX0DRTqjCU8gck25ezlc96MYUdF7jb6i4UAUemtj7/BDzVBIdvzBUL5byAfZYgzNWpO1exUjUV0YnnGyGTHSb5z3dQm/IUOBrEwhgLph5GngQ5JIPi7q8bfifb0fh2pksLrPAParvesD13absmqiUKayxCXVQfX+n4jz0rC0Mlxsvyof/0wsEHtbGOMeJxfC6j5ePZn/BM4z7vPivEGUAkLe8v64N6Q==
  template:
    metadata:
      creationTimestamp: null
      name: git-credentials
      namespace: development
    type: Opaque
