apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - apps/personal-blog
  - apps/homepage
  - apps/work-rate-calculator
  # - ghcr-credentials-sealed.yaml
  - certificate.yaml
  - development-repository.yaml
  # - git-credentials-sealed.yaml
