---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: personal-blog-ingress-production
  namespace: flux-system
spec:
  image: ghcr.io/lewi0231/home-lab-personal-blog
  interval: 1m0s
  secretRef:
    name: ghcr-credentials
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: personal-blog-policy-production
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: personal-blog-repository-production
  policy:
    # For SHA-based tags:
    # alphabetical:
    #   order: desc
    semver:
      range: ">=0.0.0"
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: personal-blog-update-production
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: "Update image: {{range .Updated.Images}}{{.Target.String}}{{end}}"
    push:
      branch: main
  update:
    path: ./clusters/homelab/environments/production/apps/personal-blog
    strategy: Setters
