---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgAa2V56MArFRwXOaj+XShNCAqFkUEe9Tjbcv95g5bWmEl+wV4aQ1BHR2pD8j77F6c+iZFEXAYXLfHnkpbEyZjwvmaaVIEtNSAYo0zEhV8HkAokTZtUGe0sNljfXtseDr1XbOWwVaXn4WnCXtXK3ozb6U6qtXf3vLg8HH5yCMxW3SPdAjIbLdZCE3TNwgANsl7Tipta8q8BdMf5FSD2bA2LB8SVXdL2+gXnH6mYI+32GysC5IJz7TST0Bckdj+12Bx1dt1qgaEd6D3kid1VyH/ZcDp6JJfkPMaWG1/pntMkfLT3u77jE+XDDT236WZ/wOYHrceWqiLS6zu5KJkl1G79Uuid7jxZYFUFzlTXCb4fmydvqUFl27cZPFuw77dWyEbdOs2VClKnURa727myhbnFyCvJoeb3RFxy1tpyoB7u158uwd/DG5zL2iCUfX5TuNm7kUm7mKUwI1V/tSwo3C/OqIhbCbd4dB5pHHF8akTDZ5NfTpEl9m3sV6PYDizhqh7Bbefmq9X2A/TYhTMusOEre2yFXxLIDeTy/BxwH90wbWR3JnmH7O58aMFo7RbXwAPRoMWL1pBcnEo0kp6vLNIyZrIeOcfoEuagknOPcx7qlxV/lMwUObMUUB+I3lCtVV72tEViaJg50j8YisQcTvroXHGAIz7N8g/CA0kz0etTd3l536v0GK2FtJ80kg6LYbam0ZqkxCY8iWgI/qs3v3Epq1LYgVue14LWL+i4r5syV5cU9UAMLKwOu
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
    type: Opaque
