---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-credentials
  namespace: production
spec:
  encryptedData:
    password: AgCh1wADIwXDJVfdW2+veja04KnZbqrJxXyFN72Zv/vmdIdDIQr05YZd45o8431hi8sPekjRrYANDgJZdO3Q2VUvRxaVZt4+8bDWEKkdoEfC0+OEmuS3B+SCJT6cvqofUIAWG1sl2QPL+q8Aaoc1vv3YTTjIpfRGQ3y4h8SxOiM6oyHqSsx1rtRTXuM7zE7fxsl9y1CGa8kYXI7wUWzPdJ1u/vJ99P2KNCroVtpL7PjAARwSDyingiO99p9Bmb5WOfsFAYidBt2eiOzdvffw96+IL98G1l/S3F6Q/9Xd3vhixYxOqH7kFdQbUIKZGLbfdL8fESzguyckW1KoY6VneRBDeedsbS4Ltnr4o4DbsNgwdC2/DnFNzn72TPIDD5iVKv/+LyLBjYQFDBWjuRiOOynR9QTaVup7TgCBF8DUCAd3RqYKQU296s9sXDi8121F5C3FJNtihQJwgIqE6m2zyBIfUl4fXCxwebDyCYBhFVZyJDp35w6upz2E3b8OZJtcjdSjEs4+Ui9tEs+T0EGbz1vdcNJDv+kkqbrGSn4xh2ThjxmK5JsKu4k4y9iFZ/8ywE/Wn6uD66285TD7T5171Ytr/IMYiwKgO9veL0kEpjrWUvcGrpi8Xbycv2AULg6mYKnNjBRO4QyftCmHjUvUluSDIbCGAntQKFirLdb25+pwWaN04EyWC5wjzCgpoqZM9lWxyVfLNpMgzZaZspP7qp68uCRrnabX/nIqHXfJsmlXpo8ENYuIn2jY
    username: AgCIH5ul75uPKYW8PBhzGoIh9W0mm+i8m4TWqRJKDxXY4lBzInsAhIf5bSqlXvTScE/LytTpuyo1wz2WxJg980J2L7DTMZCeekWl6wvLCTcjf/6BfvSzS4hUXvhTnWAHIoTK6bjqK8mm5xpJ75fNooa23d255v0GyuXChge5KMngv/w/hkVFrmjMJ102OMWQUr9f0FVbTLUPmZzbryADt4bQ7nYGuaO9e4Z5SYbrH5a/uwyk4ZTFdlWeehmPe4pk0NB0X3nBpMPr2W9wtG/YYc1i0T4TeoGKC/dmoyk++wi8E8rMwWY8LEzHYd189gvRCTqmBRxItufUd+HvbZTrGdrRyokHnrZ87t5erdkKxRVCMZ0K4/JVT6CZC7YobSVcwa8qCCYohqTS9/7CPw9CZBZM/Eo22ZVestRTRuTDiX5M/urtIPuCtokjIf+pVD0wbwEQv7b+oDqnRkpiqnzFJtVSCV0wL0n26uK33aTxCM9y+pA0e8P4ZqKUcSSt7AZs6wDGIhcdCEi6/EVkKElb1QbOogQoQi/doyD80M7KxlxhiOUpb+1P7Dihz2CtlRM39Osr3exaD6ZUP2YB9YMf+wkFkqYvgoPkCd6SoIHzVTd4TQs+McCKJ41qPLPbBMr++j7fOrd5uT16asCuN4skesg/WeNYUvqxSvNEGjaXtvUDG0Rl40peQpwMA+iHSumYVDzwKOy5rO3d1g==
  template:
    metadata:
      creationTimestamp: null
      name: git-credentials
      namespace: production
