- name: Install K3s server on first master node
  hosts: chimera
  become: true
  tasks:
    - name: Install K3s server with cluster-init
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--cluster-init" sh -
      args:
        creates: /etc/systemd/system/k3s.service

- name: Fetch K3s node token
  hosts: chimera
  become: true
  tasks:
    - name: Get K3s node token
      shell: cat /var/lib/rancher/k3s/server/node-token
      register: node_token
      changed_when: false
    - name: Set node token fact for other plays
      set_fact:
        k3s_token: "{{ node_token.stdout }}"
      delegate_to: localhost
      delegate_facts: true

- name: Install K3s on other master nodes
  hosts: master:!chimera
  become: true
  tasks:
    - name: Install K3s server on other masters
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--server https://chimera:6443 --token {{ hostvars['localhost'].k3s_token }}" sh -
      args:
        creates: /etc/systemd/system/k3s.service

- name: Install K3s agents
  hosts: agent
  become: true
  tasks:
    - name: Install K3s agent
      shell: |
        curl -sfL https://get.k3s.io | K3S_URL=https://chimera:6443 K3S_TOKEN={{ hostvars['localhost'].k3s_token }} sh -
      args:
        creates: /etc/systemd/system/k3s-agent.service
- name: Verify K3s installation
  hosts: all
  become: true
  tasks:
    - name: Check K3s service status
      command: systemctl status k3s{% if inventory_hostname in groups['agent'] %}-agent{% endif %}
      register: k3s_status
      changed_when: false
      failed_when: false

    - name: Display K3s status
      debug:
        msg: "K3s on {{ inventory_hostname }} is {{ 'running' if 'Active: active (running)' in k3s_status.stdout else 'not running' }}"
