---
- name: Fetch kubeconfig from cerberus
  hosts: cerberus
  become: true
  tasks:
    - name: Fetch k3s.yaml to local machine
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ~/Coding/homeLab/.kube/kube-config.yaml
        flat: yes

- name: Add KUBECONFIG to shell profile
  hosts: localhost
  tasks:
    - name: Ensure KUBECONFIG is set in .bashrc
      ansible.builtin.lineinfile:
        path: ~/.bashrc
        line: "export KUBECONFIG=~/Coding/homeLab/.kube/kube-config.yaml"
        create: yes
