---
- name: Fetch kubeconfig from cerberus
  hosts: cerberus
  gather_facts: true
  become: true
  tasks:
    - name: Fetch k3s.yaml to local machine
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ~/Coding/homeLab/.kube/kube-config.yaml
        flat: yes

- name: Replace localhost with master IP in kube-config
  hosts: localhost
  tasks:
    - name: Replace 127.0.0.1 with cerberus IP in kube-config
      replace:
        path: ~/Coding/homeLab/.kube/kube-config.yaml
        regexp: '127\.0\.0\.1'
        replace: "{{ hostvars['cerberus'].ansible_host }}"
# Sets Kube-config locally but needs to be run for each shell (i.e., export KUBECONFIG=)
